#!/bin/bash
PYTHONPATH="$(dirname "$0")"
export PYTHONPATH

CMD="$1"
shift

case $CMD in
  "dev")
    echo "Starting development server..."
    python3 bin/dev.py
    ;;

  "init")
    echo "Initializing Outpost..."
    python3 bin/init.py
    ;;

  "robot")
    echo "Creating robot.txt and sitemap.xml"
    python3 bin/robot.py
    ;;

  "run")
    echo "Starting production server..."
    python3 bin/run.py
    ;;

  *)
    echo "Usage: $0 {dev}"
    exit 1
    ;;
esac
